; SmartPonic ESP32 Node (38-Pin) - Sensor + LoRa Telemetry
;
; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
; board_build.flash_mode = dio
; board_build.f_cpu = 240000000L
; board_build.partitions = no_ota.csv
; board_build.flash_size = 4MB
; upload_speed = 115200
; build_flags =
; 	-I ../shared
; build_src_filter =
; 	+<main.cpp>
; 	+<SensorManager.cpp>
; 	+<PacketBuilder.cpp>
; lib_deps =
; 	sandeepmistry/LoRa@^0.8.0
; 	adafruit/DHT sensor library@^1.4.7
; 	milesburton/DallasTemperature@^4.0.6
; 	paulstoffregen/OneWire@^2.3.8
; 	mbedtls

[env:esp32dev_full]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
board_build.partitions = no_ota.csv
board_build.flash_size = 4MB
upload_speed = 115200
build_flags =
	-I ../shared
build_src_filter =
	+<main_full.cpp>
	+<SensorManager.cpp>
	+<PacketBuilder.cpp>
	+<PriorityEngine.cpp>
lib_deps =
	sandeepmistry/LoRa@^0.8.0
	adafruit/DHT sensor library@^1.4.7
	milesburton/DallasTemperature@^4.0.6
	paulstoffregen/OneWire@^2.3.8
	mbedtls