include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_dynamic_calls
    - prefer_single_quotes
    - require_trailing_commas
    - avoid_print
    - prefer_relative_imports
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - prefer_final_locals
    - no_duplicate_case_values
    - prefer_const_constructors_in_immutables
    - avoid_void_async
    - unawaited_futures
    - cancel_subscriptions
    - close_sinks
