; [env:lolin_s2_mini]
; platform = espressif32
; board = lolin_s2_mini
; framework = arduino
; monitor_speed = 115200
; build_flags = -I ../shared
; build_src_filter = +<main.cpp>
; lib_deps =
; 	sandeepmistry/LoRa@^0.8.0
; 	mbedtls
; 	bblanchon/ArduinoJson@^7.2.2

[env:lolin_s2_mini_full]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
build_flags = -I ../shared
build_src_filter = +<main_full.cpp>
lib_deps =
	sandeepmistry/LoRa@^0.8.0
	mbedtls
	bblanchon/ArduinoJson@^7.2.2