const state={nodeId:1,range:'24h',refreshMs:20000,payload:null,chartModel:null,chartHover:null,activeTab:'overview',chartNeedsResize:false,chartFrame:null,mapFull:null,mapFullMarkers:[],mapMini:null,mapMiniMarker:null};
const iconMap={thermostat:'*',droplets:'~',waves:'=',flask:'+',sparkles:'#',cloudy:'@',rain:'R'};
const sensorOrder=['temperature','humidity','waterTemp','ph','tds','turbidity','rain'];

async function loadDashboardData(){const rs=document.getElementById('refreshStatus');rs.textContent='Refreshing...';try{const r=await fetch(`dashboard_data.php?node_id=${encodeURIComponent(state.nodeId)}&limit=24&range=${encodeURIComponent(state.range)}&_=${Date.now()}`,{headers:{Accept:'application/json'},cache:'no-store'});const p=await r.json();if(!r.ok||p.error)throw new Error(p.error||'Failed to load dashboard data');state.payload=p;document.getElementById('timeRangeSelect').value=p.selected_range||state.range;renderDashboard(p);rs.textContent=`Updated ${formatDateTime(p.generated_at)}`}catch(e){rs.textContent='Refresh failed';renderError(e.message||'Unable to load dashboard data')}}
function renderDashboard(p){const n=p.node||{},s=p.summary||{},m=p.sensors||{},a=p.analytics||{};const alerts=p.alerts||[];renderNodeSelectors(p.nodes||[],n.id||state.nodeId);document.getElementById('generatedAt').textContent=`Node ${n.id||state.nodeId} | ${n.name||'Unknown'}`;document.getElementById('heroTitle').textContent=n.name||`Node ${state.nodeId}`;document.getElementById('heroSubtitle').textContent=`${n.location||'Unknown location'} | ${labelForRange(p.selected_range||state.range)} | ${p.timezone||'Local'}`;document.getElementById('metricLocation').textContent=n.location||'--';document.getElementById('metricSensors').textContent=s.configured_sensor_count??s.active_sensor_count??0;document.getElementById('metricRssi').textContent=s.rssi==null?'--':`${s.rssi} dBm`;document.getElementById('metricSnr').textContent=s.snr==null?'--':`${s.snr} dB`;document.getElementById('snapshotTime').textContent=formatRelativeTime(s.latest_reading_at);document.getElementById('latestReading').textContent=s.latest_reading_at?`Latest ${formatDateTime(s.latest_reading_at)}`:'No reading yet';document.getElementById('retentionSummary').textContent=formatRetention(p.retention_policy||p.settings?.retention_policy);document.getElementById('signalQualityCard').textContent=s.signal_quality?.label||'--';document.getElementById('alertCount').textContent=alerts.length;setNodeStatus(s.node_status);document.getElementById('retentionSelect').value=p.retention_policy||p.settings?.retention_policy||'keep_forever';renderSensorTypeFilters(m);renderSensorCards(m,alerts);renderTrendTables(m);renderActivity(p.recent_activity||[],m);renderSignalHistory(p.signal_history||[]);renderHealth(s);renderAlerts(alerts);renderCommunicationAnalytics(a,s);renderCommunicationHealthPanel(p.communication_health);renderSignalMap(s);renderCommunicationOverview(s);if(state.activeTab==='trends'){renderTrendChart(m)}else{state.chartModel=null;state.chartHover=null;hideChartTooltip()}if(state.activeTab==='map'){renderNodeMap(p.nodes||[])}}
function renderNodeSelectors(nodes,selected){document.getElementById('nodeSelect').innerHTML=nodes.map(n=>`<option value="${n.id}">${esc(n.name||`Node ${n.id}`)}</option>`).join('');document.getElementById('nodeSelect').value=String(selected);document.getElementById('exportNodeSelect').innerHTML=['<option value="all">All Nodes</option>'].concat(nodes.map(n=>`<option value="${n.id}">${esc(n.name||`Node ${n.id}`)}</option>`)).join('');document.getElementById('exportNodeSelect').value=String(selected)}
function setNodeStatus(st){const b=document.getElementById('nodeStatusBadge'),d=b.querySelector('.dot');const label=b.querySelector('span:last-child');const palette={online:'#5cf2b5',delayed:'#ffa94d',stale:'#ff8f9d',offline:'#ff8f9d'};const color=palette[st?.state]||'#9ecaff';label.textContent=st?.label||'Offline';d.style.background=color;d.style.boxShadow=`0 0 18px ${rgba(color,.55)}`;b.style.borderColor=rgba(color,.22);b.style.background=`linear-gradient(180deg, ${rgba(color,.16)}, rgba(255,255,255,.04))`}
function renderSensorTypeFilters(sensors){document.getElementById('sensorTypeFilters').innerHTML=sensorOrder.map(k=>`<label class="check"><input type="checkbox" value="${k}" checked><span>${esc(sensors[k]?.label||k)}</span></label>`).join('')}
function renderSensorCards(sensors,alerts=[]){const root=document.getElementById('sensorGrid'),list=getVisibleSensors(sensors);if(!list.length){root.innerHTML='<div class="empty">No configured sensor data found for the latest node reading yet.</div>';return}const alertMap={};alerts.forEach(alert=>{if(alert.sensor_key)alertMap[alert.sensor_key]=alert});root.innerHTML=list.map(s=>{const l=s.latest,a=s.accent||'#00fbfb',u=l&&l.display!=='--'&&s.unit!=='state'?` ${s.unit}`:'',chip=s.status==='ok'?'ok':'warn',alert=alertMap[s.key],alertClass=alert?.severity==='critical'?'card-critical':alert?'card-alert':'',alertBadge=alert?`<div class="sensor-alert-badge ${alert.severity==='critical'?'critical':'warn'}">${esc(alert.severity||'warn')}</div>`:``;return `<article class="card ${alertClass}"><div class="top"><div class="icon" style="color:${a};border:1px solid ${rgba(a,.24)};">${iconMap[s.icon]||'*'}</div><div class="row">${alertBadge}<div class="chip ${chip}">${esc(s.status||'ok')}</div></div></div><p class="name">${esc(s.label)}</p><p class="big" style="color:${a};">${l?`${esc(l.display)}${u}`:'--'}</p><svg class="spark" viewBox="0 0 220 62" preserveAspectRatio="none">${miniChart(s.history||[],a)}</svg><div class="meta"><span>${l?`GPIO ${l.pin}`:'No pin yet'}</span><span>${l?formatRelativeTime(l.created_at):'Waiting...'}</span></div></article>`}).join('')}
function renderTrendChart(sensors){const c=document.getElementById('trendChart'),ctx=c.getContext('2d'),info=document.getElementById('chartInfo'),legend=document.getElementById('chartLegend'),p=c.parentElement,ratio=Math.min(window.devicePixelRatio||1,1.5),w=p.clientWidth,h=p.clientHeight;c.width=w*ratio;c.height=h*ratio;c.style.width=`${w}px`;c.style.height=`${h}px`;ctx.setTransform(ratio,0,0,ratio,0,0);const seriesSensors=getTrendSensors(sensors).filter(s=>Array.isArray(s.history)&&s.history.some(pt=>pt.numeric!==null));info.textContent=seriesSensors.length?`${labelForRange(document.getElementById('timeRangeSelect').value)} | ${seriesSensors.length} trend line${seriesSensors.length>1?'s':''}`:`${labelForRange(document.getElementById('timeRangeSelect').value)} | No numeric history`;legend.innerHTML=seriesSensors.map(s=>`<div class="pill"><span class="swatch" style="background:${s.accent};"></span><span>${esc(s.label)}</span></div>`).join('');if(!seriesSensors.length){state.chartModel=null;state.chartHover=null;hideChartTooltip();ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(168,184,201,.9)';ctx.font='15px Inter';ctx.textAlign='center';ctx.fillText('No numeric sensor history available yet.',w/2,h/2);return}const pad={top:22,right:18,bottom:34,left:18},cw=w-pad.left-pad.right,ch=h-pad.top-pad.bottom,nums=seriesSensors.flatMap(s=>s.history.map(pt=>pt.numeric).filter(v=>v!==null)),min=Math.min(...nums),max=Math.max(...nums),range=Math.max(max-min,1),series=seriesSensors.map(s=>({sensor:s,points:s.history.filter(pt=>pt.numeric!==null).map((pt,i,rows)=>({sensor:s,point:pt,x:pad.left+cw*(i/Math.max(rows.length-1,1)),y:pad.top+ch-(((pt.numeric-min)/range)*ch)}))}));state.chartModel={w,h,pad,ch,min,max,series};drawTrendChart()}
function drawTrendChart(){const c=document.getElementById('trendChart'),ctx=c.getContext('2d'),tip=document.getElementById('chartTooltip'),m=state.chartModel;if(!m){hideChartTooltip();return}const{w,h,pad,ch,min,max,series}=m;ctx.clearRect(0,0,w,h);series.forEach(({sensor,points})=>{ctx.beginPath();ctx.lineWidth=2.25;ctx.strokeStyle=sensor.accent;points.forEach((pt,i)=>i===0?ctx.moveTo(pt.x,pt.y):ctx.lineTo(pt.x,pt.y));ctx.stroke();points.forEach(pt=>{ctx.beginPath();ctx.fillStyle=sensor.accent;ctx.arc(pt.x,pt.y,2.2,0,Math.PI*2);ctx.fill()})});ctx.fillStyle='rgba(168,184,201,.9)';ctx.font='12px Inter';ctx.textAlign='left';ctx.fillText(max.toFixed(1),pad.left,14);ctx.fillText(min.toFixed(1),pad.left,h-10);if(!state.chartHover){hideChartTooltip();return}const v=state.chartHover;ctx.beginPath();ctx.strokeStyle='rgba(255,255,255,.12)';ctx.moveTo(v.x,pad.top);ctx.lineTo(v.x,pad.top+ch);ctx.stroke();ctx.beginPath();ctx.fillStyle=v.sensor.accent;ctx.arc(v.x,v.y,4.6,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.fillStyle='#fff';ctx.arc(v.x,v.y,2,0,Math.PI*2);ctx.fill();tip.innerHTML=`<div class="tipt" style="color:${v.sensor.accent};">${esc(v.sensor.label)}: ${esc(v.point.display)} ${v.sensor.unit!=='state'?esc(v.sensor.unit):''}</div><div class="tipm">GPIO ${v.point.pin}<br>${esc(formatPointTime(v.point.created_at))}</div>`;tip.classList.add('show');tip.style.left=`${Math.min(w-170,Math.max(10,v.x+14))}px`;tip.style.top=`${Math.max(10,v.y-56)}px`}
function renderTrendTables(sensors){const root=document.getElementById('trendTableGrid'),list=getTrendSensors(sensors);if(!list.length){root.innerHTML='<div class="empty">No trend tables available yet for this node.</div>';return}root.innerHTML=list.map(s=>{const rows=(s.history||[]).slice(-6).reverse(),u=s.unit!=='state'?` ${s.unit}`:'',body=rows.length?rows.map(r=>`<tr><td>${formatRelativeTime(r.created_at)}</td><td>GPIO ${r.pin}</td><td>${esc(r.display)}${u}</td></tr>`).join(''):'<tr><td colspan="3">No history yet</td></tr>';return `<div class="tablecard"><div class="tablehead"><div><strong style="color:${s.accent};">${esc(s.label)}</strong><div class="sub">${esc(s.family||s.label)} | ${esc(s.table)}</div></div><div class="pill">${s.latest?`Now ${esc(s.latest.display)}${u}`:'No data'}</div></div><table><thead><tr><th>Time</th><th>Pin</th><th>Value</th></tr></thead><tbody>${body}</tbody></table></div>`}).join('')}
function renderActivity(items,sensors){const root=document.getElementById('activityList');if(!items.length){root.innerHTML='<div class="empty">Recent activity will appear here after new uploads.</div>';return}const colors={};Object.values(sensors).forEach(s=>colors[s.table]=s.accent);root.innerHTML=items.map(i=>`<div class="item"><div class="adot" style="background:${colors[i.table]||'#00fbfb'};"></div><div style="flex:1"><strong>${esc(i.sensor)}</strong><span>GPIO ${i.pin} | ${esc(i.table)}</span></div><div style="text-align:right"><strong>${esc(i.value)}</strong><span>${formatRelativeTime(i.created_at)}</span></div></div>`).join('')}
function renderSignalHistory(items){const root=document.getElementById('signalList');if(!items.length){root.innerHTML='<div class="empty">Signal history will appear after packets arrive.</div>';return}root.innerHTML=items.slice(-10).reverse().map(i=>`<div class="signal"><div style="flex:1"><strong>${formatRelativeTime(i.created_at)}</strong><span>${formatDateTime(i.created_at)}</span></div><div class="signal-metrics"><span class="prio-badge ${(i.priority_level||'LOW').toLowerCase()}">${i.priority_level||'LOW'}</span><span class="mode-badge">${i.report_mode||'NORMAL'}</span></div><div style="text-align:right"><strong>${i.rssi==null?'--':`${i.rssi} dBm`}</strong><span>${i.snr==null?'--':`${i.snr} dB`}</span></div></div>`).join('')}
function renderHealth(s){document.getElementById('healthStatus').textContent=s.node_status?.label||'--';document.getElementById('healthFreshness').textContent=s.latest_reading_at?formatRelativeTime(s.latest_reading_at):'--';document.getElementById('healthSignal').textContent=s.rssi!=null&&s.snr!=null?`${s.signal_quality?.label||'Unknown'} network | ${s.rssi} dBm | ${s.snr} dB`:s.rssi!=null?`${s.rssi} dBm`:'--';document.getElementById('healthPriorityMode').textContent=`${s.priority_level||'--'} / ${s.report_mode||'--'}`;document.getElementById('healthSeq').textContent=s.sequence_number!=null?`#${s.sequence_number}`:'--';document.getElementById('healthLat').textContent=s.latitude!=null?Number(s.latitude).toFixed(6):'--';document.getElementById('healthLon').textContent=s.longitude!=null?Number(s.longitude).toFixed(6):'--';document.getElementById('healthDist').textContent=s.distance_m!=null?`${Number(s.distance_m).toFixed(1)} m`:'--'}
function renderCommunicationAnalytics(a,s){const sig=a.signal_stats||{};document.getElementById('analyticsAvgRssi').textContent=sig.avg_rssi!=null?`${sig.avg_rssi} dBm`:'--';document.getElementById('analyticsAvgSnr').textContent=sig.avg_snr!=null?`${sig.avg_snr} dB`:'--';document.getElementById('analyticsMinRssi').textContent=sig.min_rssi!=null?`${sig.min_rssi} dBm`:'--';document.getElementById('analyticsMaxRssi').textContent=sig.max_rssi!=null?`${sig.max_rssi} dBm`:'--';document.getElementById('analyticsPktCount').textContent=sig.packet_count!=null?String(sig.packet_count):'--';const intervalMap={NORMAL:'15 min',ABNORMAL:'5 min',CRITICAL:'1 min'};document.getElementById('analyticsInterval').textContent=intervalMap[s.report_mode]||'--'}
function renderCommunicationHealthPanel(h){const rateEl=document.getElementById('commHealthRate');const recvEl=document.getElementById('commHealthReceived');const gapsEl=document.getElementById('commHealthGaps');const freshEl=document.getElementById('commHealthFresh');if(!h){rateEl.textContent='--';recvEl.textContent='--';gapsEl.textContent='--';freshEl.textContent='--';return}rateEl.textContent=h.delivery_rate!=null?`${h.delivery_rate}%`:'--';recvEl.textContent=`${h.total_received||0} / ${h.total_expected||0}`;gapsEl.textContent=h.sequence_gaps!=null?String(h.sequence_gaps):'--';freshEl.textContent=h.freshness_seconds!=null?`${h.freshness_seconds}s ago`:'--'}
function renderCommunicationOverview(s){const priority=s.priority_level||'--',mode=s.report_mode||'NORMAL',seq=s.sequence_number,dist=s.distance_m,lat=s.latitude,lng=s.longitude;const prioColor={'LOW':'var(--green)','MEDIUM':'var(--orange)','HIGH':'var(--red)'}[priority]||'var(--muted)';document.getElementById('commPriority').innerHTML=priority!=='--'?`<span style="color:${prioColor}">${priority}</span>`:'--';document.getElementById('commReportMode').textContent=mode;document.getElementById('commSequence').textContent=seq!=null?`#${seq}`:'--';document.getElementById('commDistance').textContent=dist!=null?`${Number(dist).toFixed(1)} m`:'--';if(lat&&lng){document.getElementById('commCoordinates').textContent=`${Number(lat).toFixed(4)}, ${Number(lng).toFixed(4)}`;document.getElementById('commLocationStatus').textContent='Location synced'}else{document.getElementById('commCoordinates').textContent='No coords';document.getElementById('commLocationStatus').textContent='No synced location'}};
function renderSignalMap(s){document.getElementById('mapRssi').textContent=s.rssi!=null?`${s.rssi} dBm`:'-- dBm';document.getElementById('mapSnr').textContent=s.snr!=null?`${s.snr} dB`:'-- dB';const lat=s.latitude,lng=s.longitude;if(!lat||!lng)return;if(!state.mapMini){state.mapMini=L.map('nodeMap',{zoomControl:true,attributionControl:false}).setView([lat,lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(state.mapMini);state.mapMiniMarker=L.circleMarker([lat,lng],{radius:8,color:'#00fbfb',fillColor:'#00fbfb',fillOpacity:0.85,weight:2}).addTo(state.mapMini)}else{state.mapMiniMarker.setLatLng([lat,lng]);state.mapMini.setView([lat,lng],state.mapMini.getZoom())}}
function renderNodeMap(nodes){const container=document.getElementById('nodeMapFull');if(!container)return;const withCoords=nodes.filter(n=>n.latitude&&n.longitude);const noCoords=nodes.filter(n=>!n.latitude||!n.longitude);document.getElementById('mapNodeCount').textContent=`${nodes.length} node${nodes.length!==1?'s':''}`;const noSection=document.getElementById('mapNoCoordsList');const noList=document.getElementById('mapNoCoordNodes');if(noCoords.length){noSection.style.display='';noList.innerHTML=noCoords.map(n=>`<div class="no-coords-item"><strong>${esc(n.name||`Node ${n.id}`)}</strong><span>${n.hardware_id?esc(n.hardware_id.slice(-6)):'--'}</span><span class="pill">${esc(n.location||'No location')}</span></div>`).join('')}else{noSection.style.display='none'}if(!withCoords.length){container.innerHTML='<div class="empty" style="padding:48px 0;text-align:center">No nodes have reported a GPS location yet. Configure node coordinates via the Flutter app.</div>';return}if(!state.mapFull){state.mapFull=L.map('nodeMapFull',{zoomControl:true,attributionControl:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(state.mapFull);L.control.attribution({prefix:'<a href="https://leafletjs.com">Leaflet</a> | &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(state.mapFull)}state.mapFullMarkers.forEach(m=>m.remove());state.mapFullMarkers=[];const bounds=[];withCoords.forEach(n=>{const isSelected=String(n.id)===String(state.nodeId);const color=isSelected?'#5cf2b5':'#9ecaff';const marker=L.circleMarker([n.latitude,n.longitude],{radius:isSelected?11:8,color:color,fillColor:color,fillOpacity:0.85,weight:2}).addTo(state.mapFull);const hwLabel=n.hardware_id?`<span style="font-family:monospace;font-size:.78rem">${esc(n.hardware_id)}</span>`:'';marker.bindPopup(`<div style="min-width:160px"><strong>${esc(n.name||`Node ${n.id}`)}</strong><br>${hwLabel}<br><span style="color:#9ab">${esc(n.location||'No label')}</span><br><small>${Number(n.latitude).toFixed(6)}, ${Number(n.longitude).toFixed(6)}</small></div>`);state.mapFullMarkers.push(marker);bounds.push([n.latitude,n.longitude])});if(bounds.length===1){state.mapFull.setView(bounds[0],15)}else{state.mapFull.fitBounds(bounds,{padding:[32,32]})}}
function renderAlerts(items){const root=document.getElementById('alertList');if(!items.length){root.innerHTML='<div class="empty">No active alerts. Latest values are inside the saved ranges.</div>';return}root.innerHTML=items.map(a=>{const dbStatus=a.db_status||'active';const isResolved=dbStatus==='resolved';const isAcked=dbStatus==='acknowledged';const showAckBtn=!isResolved&&!isAcked&&a.severity!=='critical';const showResBtn=!isResolved;return`<div class="alert"><div class="row spread top-align"><div><strong>${esc(a.label)}</strong><p>${esc(a.message)}</p></div><div class="chip ${a.severity==='critical'?'critical':'warn'}">${esc(a.severity||'warning')}${isAcked?' &nbsp;⏳':isResolved?' &nbsp;✓':''}</div></div><div class="sub top-gap">${a.created_at?formatDateTime(a.created_at):'No timestamp'}</div>${(showAckBtn||showResBtn)?`<div class="alert-actions" style="margin-top:10px;display:flex;gap:8px;">${showAckBtn?`<button class="btn alt" style="padding:6px 12px;font-size:.75rem" onclick="acknowledgeAlert('${a.sensor_key}')">Acknowledge</button>`:''}${showResBtn?`<button class="btn alt" style="padding:6px 12px;font-size:.75rem" onclick="resolveAlert('${a.sensor_key}')">Resolve</button>`:''}</div>`:''}</div>`}).join('')}
function getVisibleSensors(s){const list=sensorOrder.map(k=>s[k]).filter(Boolean),cfg=list.filter(v=>v.configured);return cfg.length?cfg:list.filter(v=>v.latest)}
function getTrendSensors(s){const list=sensorOrder.map(k=>s[k]).filter(Boolean),h=list.filter(v=>Array.isArray(v.history)&&v.history.length>0);return h.length?h:list.filter(v=>v.latest)}
function miniChart(h,a){const n=h.filter(i=>i.numeric!==null);if(n.length<2)return `<rect x="0" y="30" width="220" height="2" fill="${rgba(a,.18)}"></rect>`;const vals=n.map(i=>i.numeric),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1),pts=n.map((i,x)=>`${(220*x)/Math.max(n.length-1,1)},${56-(((i.numeric-min)/range)*46)}`).join(' ');return `<polyline fill="none" stroke="${rgba(a,.18)}" stroke-width="10" stroke-linecap="round" stroke-linejoin="round" points="${pts}"></polyline><polyline fill="none" stroke="${a}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" points="${pts}"></polyline>`}
function hideChartTooltip(){document.getElementById('chartTooltip').classList.remove('show')}
function requestChartDraw(){if(state.chartFrame)return;state.chartFrame=window.requestAnimationFrame(()=>{state.chartFrame=null;drawTrendChart()})}
function renderError(msg){document.getElementById('sensorGrid').innerHTML=`<div class="empty">${esc(msg)}</div>`;document.getElementById('trendTableGrid').innerHTML='<div class="empty">No trend tables available.</div>';document.getElementById('activityList').innerHTML='<div class="empty">No activity to show.</div>';document.getElementById('signalList').innerHTML='<div class="empty">No signal data to show.</div>';document.getElementById('alertList').innerHTML='<div class="empty">Alerts unavailable.</div>'}
async function postJson(url,payload){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Request failed');return d}
async function acknowledgeAlert(sensorKey){try{await postJson('dashboard_manage.php',{action:'acknowledge_alert',node_id:state.nodeId,sensor_key:sensorKey});loadDashboardData()}catch(e){alert(e.message)}}
async function resolveAlert(sensorKey){try{await postJson('dashboard_manage.php',{action:'resolve_alert',node_id:state.nodeId,sensor_key:sensorKey});loadDashboardData()}catch(e){alert(e.message)}}
function selectedTypes(){return Array.from(document.querySelectorAll('#sensorTypeFilters input:checked')).map(i=>i.value)}
function exportUrl(format,all=false){const ep=format==='csv'?'export_data.php':'export_excel.php',q=new URLSearchParams();q.set('node_id',document.getElementById('exportNodeSelect').value||state.nodeId);const types=selectedTypes();if(types.length&&types.length<sensorOrder.length)q.set('sensor_types',types.join(','));const df=document.getElementById('exportDateFrom').value,dt=document.getElementById('exportDateTo').value;if(df)q.set('date_from',df);if(dt)q.set('date_to',dt);if(all)q.set('all','1');q.set('_',Date.now());return `${ep}?${q.toString()}`}
function formatDateTime(v){if(!v)return'--';const d=new Date(v.replace(' ','T'));return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function formatPointTime(v){if(!v)return'--';const d=new Date(v.replace(' ','T'));return Number.isNaN(d.getTime())?v:d.toLocaleString([],{hour:'2-digit',minute:'2-digit',second:'2-digit',day:'2-digit',month:'short'})}
function formatRelativeTime(v){if(!v)return'--';const d=new Date(v.replace(' ','T'));if(Number.isNaN(d.getTime()))return v;const m=Math.round((Date.now()-d.getTime())/60000);if(m<1)return'just now';if(m<60)return`${m}m ago`;const h=Math.round(m/60);if(h<24)return`${h}h ago`;return`${Math.round(h/24)}d ago`}
function labelForRange(v){return{'1h':'Last 1 hour','6h':'Last 6 hours','24h':'Last 24 hours','7d':'Last 7 days','30d':'Last 30 days'}[v]||'Selected range'}
function formatRetention(v){return{keep_forever:'Keep Forever','30_days':'Keep 30 Days','90_days':'Keep 90 Days','1_year':'Keep 1 Year'}[v]||'--'}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function rgba(hex,a){const c=hex.replace('#',''),n=parseInt(c,16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return`rgba(${r}, ${g}, ${b}, ${a})`}
document.getElementById('nodeSelect').addEventListener('change',e=>{state.nodeId=e.target.value;loadDashboardData()});
document.getElementById('timeRangeSelect').addEventListener('change',e=>{state.range=e.target.value;loadDashboardData()});
document.getElementById('refreshButton').addEventListener('click',loadDashboardData);
document.getElementById('saveSettingsButton').addEventListener('click',async()=>{try{await postJson('dashboard_manage.php',{action:'save_settings',settings:{retention_policy:document.getElementById('retentionSelect').value,default_range:document.getElementById('timeRangeSelect').value}});loadDashboardData()}catch(e){alert(e.message)}});
document.getElementById('exportButton').addEventListener('click',()=>window.open(exportUrl(document.getElementById('exportFormatSelect').value,false),'_blank'));
document.getElementById('exportAllButton').addEventListener('click',()=>window.open(exportUrl(document.getElementById('exportFormatSelect').value,true),'_blank'));
document.getElementById('exportConfigButton').addEventListener('click',()=>window.open(`dashboard_config.php?node_id=${encodeURIComponent(state.nodeId)}&_=${Date.now()}`,'_blank'));
document.getElementById('importConfigButton').addEventListener('click',()=>document.getElementById('configFileInput').click());
document.getElementById('configFileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{await postJson('dashboard_manage.php',{action:'import_snapshot',node_id:Number(state.nodeId),snapshot:JSON.parse(await f.text())});loadDashboardData()}catch(err){alert(err.message||'Failed to import config snapshot')}finally{e.target.value=''}});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.tab;state.activeTab=t;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.paneltab').forEach(p=>p.classList.toggle('active',p.dataset.panel===t));if(t==='trends'&&state.payload)renderTrendChart(state.payload.sensors||{});if(t!=='trends')hideChartTooltip();if(t==='map'&&state.payload){renderNodeMap(state.payload.nodes||[]);setTimeout(()=>{if(state.mapFull)state.mapFull.invalidateSize();if(state.mapMini)state.mapMini.invalidateSize()},120)}}));
document.getElementById('trendChart').addEventListener('mousemove',e=>{const m=state.chartModel;if(!m||state.activeTab!=='trends')return;const rect=e.target.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;let near=null,d=Infinity;m.series.forEach(({sensor,points})=>points.forEach(p=>{const dx=p.x-x,dy=p.y-y,dist=(dx*dx)+(dy*dy);if(dist<d){d=dist;near={...p,sensor}}}));state.chartHover=d<900?near:null;requestChartDraw()});
document.getElementById('trendChart').addEventListener('mouseleave',()=>{state.chartHover=null;requestChartDraw()});
window.addEventListener('resize',()=>{if(state.payload&&state.activeTab==='trends')renderTrendChart(state.payload.sensors||{})});
loadDashboardData();setInterval(loadDashboardData,state.refreshMs);setInterval(()=>{if(!state.payload?.summary)return;document.getElementById('snapshotTime').textContent=formatRelativeTime(state.payload.summary.latest_reading_at)},30000);
